apps/cart/urls.py
from django.urls import path
from . import views

app_name = 'eshop_proj'
urlpatterns = [
    path('cart/', views.cart, name="cart"),
    path('add-to-cart/<str:prod_id>/<int:id>', views.addtocart, name="addtocart"),
    path('delete/<int:id>', views.deleteItemCart, name="deleteItem"),
    path('inc/<str:prod_id>/<int:id>', views.qtyInc, name="qtyInc"),
    path('dec/<int:id>', views.qtyDec, name="qtyDec"),
    path('qty/<int:id>', views.qty, name="qty"),
]

apps/products/urls.py
from django.urls import path
from . import views

app_name = 'eshop_proj'
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:slug>/pid=<str:prod_id>/', views.productDetails, name='productDetails'),
    path('shop/<int:id>/', views.shop, name='shop')
]

eshop_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='home')),
    path('', include('contact.urls', namespace='contact')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('wishlist.urls', namespace='wishlist')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('feedback.urls', namespace='feedback')),
]

if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cart/models.py
from django.db import models
from products.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.product.prod_id

    def totalprod_price(self):
        price = self.product.sell_price * self.quantity
        return price

apps/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from products.models import Product
 

def cart(request):
    carts = Cart.objects.filter(user=request.user).order_by('-id')
    def sub_total_price():
        sub_total_price = 0
        for item in carts:
            sub_total_price = sub_total_price + item.totalprod_price()
        return sub_total_price
    if sub_total_price()  >= 500.0:
        shipping_charge = 0
    else:
        shipping_charge = 50.0
    context = {'carts':carts, 'sub_total_price': sub_total_price(),'tprice':sub_total_price()+shipping_charge, 'shipping_charge':shipping_charge}
    return render(request, 'cart/cart.html', context)

def addtocart(request, prod_id, id):
    product = Product.objects.get(prod_id=prod_id, id=id)
    carts = Cart.objects.filter(user=request.user).order_by('-id')
    if request.method == 'POST':
        if product.prod_id not in [_.product.prod_id for _ in carts]:
            cart = Cart.objects.create(user=request.user, product=product)
        else:
            return redirect('cart:qtyInc', prod_id, id)
    return redirect('cart:cart')

def deleteItemCart(request, id):
    #product = Product.objects.get(id=id)
    cart = Cart.objects.get(id=id)
    if request.method == 'POST':
        cart.delete()
    return redirect('cart:cart')

def qtyInc(request, prod_id, id):
    print(prod_id)
    cart = get_object_or_404(Cart, product__prod_id=prod_id, product__id=id, user=request.user)
    print(cart)
    print(id)
    cart.quantity += 1
    cart.save()
    return redirect('cart:cart')

def qtyDec(request, id):
    cart = get_object_or_404(Cart, id=id, user=request.user)
    cart.quantity -= 1
    cart.save()
    if cart.quantity == 0:
        cart.delete()
    return redirect('cart:cart')

def qty(request, id):
    cart = get_object_or_404(Cart, id=id, user=request.user)
    qty = request.POST.get('quantity')
    try:
        if int(qty) == 0:
            cart.delete()
        if qty > 0:
            cart.quantity = qty
            cart.save()
    except:
        return redirect('cart:cart')
    return redirect('cart:cart')

templates/cart/cart.html
{% extends 'base/base.html' %}
{% load static %}
<head>
    {% block title %}
    <title>Cart | E-Shopper</title>
	{% endblock %}
</head><!--/head-->

<body>
	{% block content %}
	<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="{% url 'home:index' %}">Home</a></li>
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>
			{% if carts %}
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="srno">SrNo</td>
							<td class="image">Image</td>
							<td class="description">Item</td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td class="remove">Remove</td>
						</tr>
					</thead>
					<tbody>
						{% for item in carts %}
						<tr>
							<td class="serial_number text-center">
								<h4>{{forloop.counter}}</h4>
							</td>
							<td class="cart_product">
								<a href="{% url 'home:productDetails' item.product.slug item.product.prod_id %}"><img src="{{item.product.main_image.url}}" alt="" style="width:100px"></a>
							</td>
							<td class="cart_description">
								<h4><a href="{% url 'home:productDetails' item.product.slug item.product.prod_id %}">{{item.product.title}}</a></h4>
								<p>{{item.product.prod_id}}</p>
							</td>
							<td class="cart_price">
								<p>{{item.product.sell_price}}</p>
							</td>
							<td class="cart_quantity">
								<span class="cart_quantity_button">
									<a class="cart_quantity_down" href="{% url 'cart:qtyDec' item.id %}"> - </a>
									<form class="form-inline" action="{% url 'cart:qty' item.id %}" method="POST">
										{% csrf_token %}
										<input class="cart_quantity_input" type="text" name="quantity" value="{{item.quantity}}" autocomplete="off" size="2">
									</form>
									<a href="{% url 'cart:qtyInc' item.product.prod_id item.product.id %}" class="cart_quantity_up" > + </a>
								</span>
							</td>
							<td class="cart_total">
								<p class="cart_total_price">{{item.totalprod_price}}</p>
							</td>
							<td class="cart_delete">
								<form action="{% url 'cart:deleteItem' item.id %}" method='post'>
									{% csrf_token  %}
									<button class="cart_quantity_delete"><i class="fa fa-times"></i></button>
								</form>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</section> <!--/#cart_items-->

	<section id="do_action">
		<div class="container">
			<div class="heading">
				<h3>What would you like to do next?</h3>
				<p>Choose if you have a discount code or reward points you want to use or would like to estimate your delivery cost.</p>
			</div>
			<div class="row">
				<div class="col-sm-6">
					<div class="chose_area">
						<ul class="user_option">
							<li>
								<input type="checkbox">
								<label>Use Coupon Code</label>
							</li>
							<li>
								<input type="checkbox">
								<label>Use Gift Voucher</label>
							</li>
							<li>
								<input type="checkbox">
								<label>Estimate Shipping & Taxes</label>
							</li>
						</ul>
						<ul class="user_info">
							<li class="single_field">
								<label>Country:</label>
								<select>
									<option>United States</option>
									<option>Bangladesh</option>
									<option>UK</option>
									<option>India</option>
									<option>Pakistan</option>
									<option>Ucrane</option>
									<option>Canada</option>
									<option>Dubai</option>
								</select>
								
							</li>
							<li class="single_field">
								<label>Region / State:</label>
								<select>
									<option>Select</option>
									<option>Dhaka</option>
									<option>London</option>
									<option>Dillih</option>
									<option>Lahore</option>
									<option>Alaska</option>
									<option>Canada</option>
									<option>Dubai</option>
								</select>
							
							</li>
							<li class="single_field zip-field">
								<label>Zip Code:</label>
								<input type="text">
							</li>
						</ul>
						<a class="btn btn-default update" href="">Get Quotes</a>
						<a class="btn btn-default check_out" href="">Continue</a>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="total_area">
						<ul>
							<li>Cart Sub Total <span>{{sub_total_price}}</span></li>
							<li>Shipping Cost <span>{% if shipping_charge == 0 %}Free{% else %}{{shipping_charge}}{% endif %}</span></li>
							<li>Total <span>{{tprice}}</span></li>
						</ul>
							<a class="btn btn-default update" href="">Update</a>
							<a class="btn btn-default check_out" href="">Check Out</a>
					</div>
				</div>
			</div>
		</div>
		{% else %}
		<div class="col-md-6 col-md-offset-3 mb-3">
			<h4>Looks like your cart is empty. Add some items to display.</h4><br>
			<img src="{% static 'images/cart/empty-cart.svg' %}" width="70%">
		</div><br>
	</section><!--/#do_action-->
	{% endif %}
{% endblock %}
</body>