apps/cart/urls.py
from django.urls import path
from . import views

app_name = 'eshop_proj'
urlpatterns = [
    path('cart/', views.cart, name="cart"),
    path('add-to-cart/<str:prod_id>/<int:id>', views.addtocart, name="addtocart"),
    path('delete/<int:id>', views.deleteItemCart, name="deleteItem"),
    path('inc/<str:prod_id>/<int:id>', views.qtyInc, name="qtyInc"),
    path('dec/<int:id>', views.qtyDec, name="qtyDec"),
    path('qty/<int:id>', views.qty, name="qty"),
]

apps/products/urls.py
from django.urls import path
from . import views

app_name = 'eshop_proj'
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:slug>/pid=<str:prod_id>/', views.productDetails, name='productDetails'),
    path('shop/<int:id>/', views.shop, name='shop')
]

eshop_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='home')),
    path('', include('contact.urls', namespace='contact')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('wishlist.urls', namespace='wishlist')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('feedback.urls', namespace='feedback')),
]

if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/products/models.py
from django.db import models
import datetime
from django.utils.text import slugify

class CarouselImage(models.Model):
    title = models.CharField(max_length=50, blank=True, null=True)
    desc = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='products/carousel_img', blank=True, null=True)
    def __str__(self):
        return self.title

class Category(models.Model):
    category = models.CharField(max_length=100, unique=True, blank=True, null=True)
    def __str__(self):
        return self.category
    class Meta:
        verbose_name_plural = 'categories'

class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete = models.CASCADE, blank=True, null=True)
    sub_category = models.CharField(max_length=100, blank=True, null=True)
    sub_cat_image = models.ImageField(upload_to='products/sub-category-image', blank=True, null=True) 
    def __str__(self):
        return self.sub_category + '-' + self.category.category
    class Meta:
        verbose_name_plural = 'sub categories'

class Brand(models.Model):
    brand = models.CharField(max_length=100, unique=True)
    enable = models.BooleanField(default=True)
    def __str__(self):
        return self.brand

class Product(models.Model):
    prod_id = models.CharField(max_length=10, unique=True, blank=True, null=True)
    title = models.CharField(max_length=100)
    s_desc = models.CharField(max_length=100, null=True, blank=True)
    l_desc = models.TextField(null=True, blank=True)
    main_image = models.ImageField(upload_to='products/', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete= models.CASCADE, blank=True, null=True)
    sub_category = models.ForeignKey(SubCategory, on_delete= models.CASCADE, blank=True, null=True)
    brand = models.ForeignKey(Brand, on_delete= models.CASCADE, blank=True, null=True)
    colours = models.CharField(max_length=50, blank=True, null=True)
    mrp = models.FloatField(null=True, blank=True)
    sell_price =models.FloatField(null=True, blank=True)
    released_on = models.DateTimeField(auto_now_add= True)
    updated_on = models.DateTimeField(auto_now=True)
    slug = models.SlugField(null=True, blank=True)
    enable = models.BooleanField(default=True)
    stock = models.BooleanField(default=True)

    def __str__(self):
        return self.prod_id + '-' + self.title

    def save(self, *args, **kwargs):
        #self.prod_id = self.prod_id + str(self.id)
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Products'

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/product_sub_images')
    def __str__(self):
        return str(self.product.prod_id) +'-'+str(self.id)

class FeatureItem(models.Model):
    item = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True)
    
    def __str__(self):
        return self.item.title + '-' + self.item.prod_id
    

apps/products/forms.py
from django import forms
from .models import Product

apps/products/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Sidebar components
class Sidebar():
    categories = Category.objects.all()
    brands = Brand.objects.filter(enable=True).order_by('-id')


def index(request, *args, **kwargs):
    carouselimgs = CarouselImage.objects.all().order_by('-id')
    categories = Sidebar.categories
    brands = Sidebar.brands
    new_products = Product.objects.all().order_by('-id')
    # for products in new arrival carousel 
    def prodlist():
        new_list = []
        new_final = []
        for prod in new_products:
            new_list.append(prod)
            if len(new_list) == 3: # 3 items in each slider
                new_final.append(new_list)
                new_list=[]
        return new_final 
    featureItems = FeatureItem.objects.all().order_by('-id')
    context={'carouselimgs':carouselimgs,'featureItems':featureItems, 'categories':categories, 'brands':brands, 'new_products':new_products,'prodlist':prodlist()}
    return render(request, 'products/index.html', context)

def productDetails(request, slug, prod_id):
    categories = Sidebar.categories
    brands = Sidebar.brands
    featureItems = FeatureItem.objects.all()
    product = get_object_or_404(Product, prod_id=prod_id)
    context={"product":product,'featureItems':featureItems, 'categories':categories, 'brands':brands}
    return render(request, 'products/product-details.html', context)

    
def shop(request, id):
    categories = Sidebar.categories
    sub_cat_obj = get_object_or_404(SubCategory, id=id)
    products = Product.objects.filter(sub_category__id = id)
    try:
        max_value = 10**int(len(str(int(max([product.sell_price for product in products])))))
    except:
        max_value = 0
    selected_value_min=0
    selected_value_max=max_value
    if request.method == "POST":
        try:
            slider = request.POST.get('slider')
            slider_list = [x for x in slider.split(',')]
            selected_value_min=slider_list[0]
            selected_value_max=slider_list[1]
            products = Product.objects.filter(sub_category__id = id, sell_price__range = (slider_list[0], slider_list[1]))
        except:
            products = Product.objects.filter(sub_category__id = id)

    print('slider',selected_value_min)   
    items = sub_cat_obj.product_set.all()
    brands_list =[]
    price_slider = True
    for item in items:
        brands_list.append(item.brand)
    brands = tuple(brands_list)
    page = request.GET.get('page', 1)
    paginator = Paginator(products, 15)
    try:
        pg = paginator.page(page)
    except PageNotAnInteger:
        pg = paginator.page(1)
    except EmptyPage:
        pg = paginator.page(paginator.num_pages)
    products_after_pagiation = pg
    context = {'max_value':max_value, 'price_slider':price_slider, 'categories':categories, 'brands':brands, 'sub_cat_obj':sub_cat_obj, 'products':products_after_pagiation, 'page':pg, 'selected_value_min':selected_value_min, 'selected_value_max':selected_value_max}
    return render(request, 'products/shop.html', context)

templates/products/index.html
{% extends 'base/base.html' %}
{% load static %}
{% load numslides %}
<html lang="en">
<head>
	{% block title %}
    <title>Home | E-Shopper</title>
	{% endblock %}
</head><!--/head-->

<body>
	{% block content %}
	<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							{% for carouselimg in carouselimgs %}
							<li data-target="#slider-carousel" data-slide-to="{{forloop.counter0}}" class="{% if forloop.counter == 1 %}active{% endif %}"></li>
							{% endfor %}
						</ol>
						
						<div class="carousel-inner">
							{% for carouselimg in carouselimgs %}
							<div class="item {% if forloop.counter == 1 %}active{% endif %}">
								<div class="col-sm-6 {% if forloop.counter == 2 %}pull-right{% endif %}">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>{{carouselimg.title}}</h2>
									<p>{{carouselimg.desc}}</p>
								</div>
								<div class="col-sm-6">
									<img src="{{carouselimg.image.url}}" class="img-responsive" alt="" />
								</div>
							</div>
							{% endfor %}
						</div>
						
						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>
				</div>
			</div>
		</div>
	</section><!--/slider-->
	
	<section>
		<div class="container">
			<div class="row">
				{% include 'common/sidebar.html' %}
				<div class="col-sm-9 padding-right">	
					<div class="recommended_items"><!--features_items-->
						<h2 class="title text-center">New Arrivals</h2>
						<div id="slider-carousel-prod" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner">
								{% for prod in prodlist %}
								<div class="item {% if forloop.counter == 1 %}active{% endif %}">
									{% for product in prod %}
									{% if product.enable %}
									{% if product.stock %}
									<div class="col-xs-4 col-md-4 col-sm-4 ">				
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="{{product.main_image.url}}" alt="" />
													<h2>₹{{product.sell_price}}</h2>
													<p>{{product.title}}</p>
													<a href="{% url 'home:productDetails' product.slug product.prod_id %}" class="btn btn-default add-to-cart">Details</a>
												</div>
												<div class="product-overlay">
													<div class="overlay-content">
														<h2>₹{{product.sell_price}}</h2>
														<p>{{product.s_desc}}</p>
														<a href="{% url 'home:productDetails' product.slug product.prod_id %}" class="btn btn-default add-to-cart">Details</a>
													</div>
												</div>
											</div>
											<div class="choose">
												<ul class="nav nav-pills nav-justified">
													<li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
													<li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
												</ul>
											</div>
										</div>
									</div>
									{% endif %}
									{% endif %}
									{% endfor %}	
								</div>
								{% endfor %}
							</div>
							
							<a href="#slider-carousel-prod" class="left control-carousel " data-slide="prev">
								<i class="fa fa-angle-left"></i>
							</a>
							<a href="#slider-carousel-prod" class="right control-carousel " data-slide="next">
								<i class="fa fa-angle-right"></i>
							</a>
						</div>

					</div><!--features_items-->
					
					<div class="category-tab"><!--category-tab-->
						<div class="col-sm-12">
							<ul class="nav nav-tabs">
								{% for product in categories %}
								<li class="{% if forloop.counter == 1 %}active{% endif %}"><a href="#{{product.category}}" data-toggle="tab">{{product.category}}</a></li>
								{% endfor %}
							</ul>
						</div>
						
						<div class="tab-content">	
							{% for product in categories %}	
							<div class="tab-pane fade {% if forloop.counter == 1 %}active in{% endif %}" id="{{product.category}}" >
								{% for item in product.subcategory_set.all|slice:":4" %}
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<a href="{% url 'home:shop' item.id %}">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="{{item.sub_cat_image.url}}" alt="" />
													<h2>₹ 500-2000</h2>
													<p>{{item.sub_category}}</p>
												</div>	
											</div>
										</a>
									</div>
								</div>
								{% endfor %}
							</div>
							{% endfor %}
						</div>	
						
					</div><!--/category-tab-->
					
					<div class="recommended_items"><!--recommended_items-->
						<h2 class="title text-center">recommended items</h2>
						
						<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner">
								<div class="item active">	
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend1.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
												
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend2.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
												
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend3.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
												
											</div>
										</div>
									</div>
								</div>
								<div class="item">	
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend1.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
												
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend2.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
												
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend3.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												</div>
												
											</div>
										</div>
									</div>
								</div>
							</div>
							 <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
								<i class="fa fa-angle-left"></i>
							  </a>
							  <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
								<i class="fa fa-angle-right"></i>
							  </a>			
						</div>
					</div><!--/recommended_items-->
					
				</div>
			</div>
		</div>
	</section>
	{% endblock %}
</body>
</html>

templates/products/product-details.html
{% extends 'base/base.html' %}
{% load static %}
<head>
    {% block title %}
    <title>Product Details | E-Shopper</title>
	{% endblock %}
</head><!--/head-->

<body>
	{% block content %}
	<section>
		<div class="container">
			<div class="row">
				{% include 'common/sidebar.html' %}	
				<div class="col-sm-9 padding-right">
					<div class="product-details"><!--product-details-->
						<div class="col-sm-5">
							<div class="view-product">
								
								<div class="tab-content">	
									{% for itemimg in product.productimage_set.all %}	
									<div class="tab-pane fade {% if forloop.counter == 1 %}active in{% endif %}" id="{{product.id}}{{itemimg.id}}" ><!--{{product.id}}{{itemimg.id }} To avoid conflicting id's of sidebar-->
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="{{itemimg.image.url}}" alt="" />		
												</div>	
											</div>
										</div>
									</div>
									{% endfor %}
								</div>
							</div>
						</div>
						
						<div class="col-sm-7">
							<div class="product-information"><!--/product-information-->
								<h2>{{product.title}}</h2>
								<p>PRODUCT ID: {{product.prod_id}}</p>
								<img src="{% static 'images/product-details/rating.png' %}" alt="" />
								<div>
									<h5>MRP: ₹ {{product.mrp}}</h5>
									<h3>₹ {{product.sell_price}}</h3>
								</div>
								<p><b>Availability:</b> {% if product.stock %}In Stock{% else %}Out of Stock {% endif %}</p>
								<p><b>Brand:</b> {{product.brand.brand}}</p>
								<span>
									<button type="button" class="btn btn-fefault cart">
										<i class="fa fa-star"></i>
										Add to wishlist
									</button>
									<form action="{% url 'cart:addtocart' product.prod_id product.id %}" method="post">
										{% csrf_token %}
										<button type="submit" class="btn btn-fefault cart">
											<i class="fa fa-shopping-cart"></i>
											Add to cart
										</button>
									</form>
								</span>
							</div><!--/product-information-->
						</div>
					</div><!--/product-details-->
					<!--image category-tab-->
					<div class="col-sm-12">
						<ul class="nav nav-tabs">
							{% for itemimg in product.productimage_set.all %}
							<li class="{% if forloop.counter == 1 %}active{% endif %}"><a class="thumbnail" href="#{{product.id}}{{itemimg.id}}" data-toggle="tab">
								<img src="{{itemimg.image.url}}" style="width:60px; height:60px"></a>
							</a></li>
							{% endfor %}
						</ul>
					</div>	
					<!--/image category-tab-->
					
					<div class="category-tab shop-details-tab"><!--category-tab-->
						<div class="col-sm-12">
							<ul class="nav nav-tabs">
								<li><a href="#details" data-toggle="tab">Details</a></li>
								<li><a href="#companyprofile" data-toggle="tab">Company Profile</a></li>
								<li><a href="#tag" data-toggle="tab">Tag</a></li>
								<li class="active"><a href="#reviews" data-toggle="tab">Reviews (5)</a></li>
							</ul>
						</div>
						<div class="tab-content">
							<div class="tab-pane fade" id="details" >
								<div class="product-image-wrapper">
									<div class="single-products">
										<div class="productinfo text-center">
											<h4>{{product.s_desc}}</h4>
											<p>{{product.l_desc}}</p>
										</div>
									</div>
								</div>
							</div>
							
							<div class="tab-pane fade" id="companyprofile" >
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="images/home/gallery1.jpg" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="images/home/gallery3.jpg" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="images/home/gallery2.jpg" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="images/home/gallery4.jpg" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
							</div>
							
							<div class="tab-pane fade" id="tag" >
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="images/home/gallery1.jpg" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="images/home/gallery2.jpg" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="images/home/gallery3.jpg" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="product-image-wrapper">
										<div class="single-products">
											<div class="productinfo text-center">
												<img src="images/home/gallery4.jpg" alt="" />
												<h2>$56</h2>
												<p>Easy Polo Black Edition</p>
												<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
											</div>
										</div>
									</div>
								</div>
							</div>
							
							<div class="tab-pane fade active in" id="reviews" >
								<div class="col-sm-12">
									<ul>
										<li><a href=""><i class="fa fa-user"></i>EUGEN</a></li>
										<li><a href=""><i class="fa fa-clock-o"></i>12:41 PM</a></li>
										<li><a href=""><i class="fa fa-calendar-o"></i>31 DEC 2014</a></li>
									</ul>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
									<p><b>Write Your Review</b></p>
									
									<form action="#">
										<span>
											<input type="text" placeholder="Your Name"/>
											<input type="email" placeholder="Email Address"/>
										</span>
										<textarea name="" ></textarea>
										<b>Rating: </b> <img src="images/product-details/rating.png" alt="" />
										<button type="button" class="btn btn-default pull-right">
											Submit
										</button>
									</form>
								</div>
							</div>
							
						</div>
					</div><!--/category-tab-->
					
					<div class="recommended_items"><!--recommended_items-->
						<h2 class="title text-center">recommended items</h2>
						
						<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner">
								<div class="item active">	
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend1.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
												</div>
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend2.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
												</div>
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend3.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="item">	
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend1.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
												</div>
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend2.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
												</div>
											</div>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="product-image-wrapper">
											<div class="single-products">
												<div class="productinfo text-center">
													<img src="images/home/recommend3.jpg" alt="" />
													<h2>$56</h2>
													<p>Easy Polo Black Edition</p>
													<button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
							 <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
								<i class="fa fa-angle-left"></i>
							  </a>
							  <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
								<i class="fa fa-angle-right"></i>
							  </a>			
						</div>
					</div><!--/recommended_items-->
					
				</div>
			</div>
		</div>
	</section>
	{% endblock %}
</body>