apps/accounts/urls.py
from django.urls import path
from . import views

app_name='eshop_proj'
urlpatterns = [
    path('login/', views.userLogin, name='login'), 
    path('logout/', views.userLogout, name='logout'),
    path('register/', views.acc_register, name='register'),
]

apps/cart/urls.py
from django.urls import path
from . import views

app_name = 'eshop_proj'
urlpatterns = [
    path('cart/', views.cart, name="cart"),
    path('add-to-cart/<str:prod_id>/<int:id>', views.addtocart, name="addtocart"),
    path('delete/<int:id>', views.deleteItemCart, name="deleteItem"),
    path('inc/<str:prod_id>/<int:id>', views.qtyInc, name="qtyInc"),
    path('dec/<int:id>', views.qtyDec, name="qtyDec"),
    path('qty/<int:id>', views.qty, name="qty"),
]

apps/contact/urls.py
from django.urls import path
from . import views

app_name = 'eshop_proj'
urlpatterns = [
    path('contact/', views.contact, name='contactus'),
]

apps/products/urls.py
from django.urls import path
from . import views

app_name = 'eshop_proj'
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:slug>/pid=<str:prod_id>/', views.productDetails, name='productDetails'),
    path('shop/<int:id>/', views.shop, name='shop')
]

eshop_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='home')),
    path('', include('contact.urls', namespace='contact')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('wishlist.urls', namespace='wishlist')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('feedback.urls', namespace='feedback')),
]

if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/common/footer.html
{% load static %}
<footer id="footer"><!--Footer-->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="companyinfo">
                        <h2><span>e</span>-shopper</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="images/home/iframe1.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                    
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="images/home/iframe2.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                    
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="images/home/iframe3.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                    
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="images/home/iframe4.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="address">
                        <img src="{% static 'images/home/map.png' %}" alt="" />
                        <p>World Is One</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Service</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Online Help</a></li>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Order Status</a></li>
                            <li><a href="#">Change Location</a></li>
                            <li><a href="#">FAQ’s</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Quock Shop</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">T-Shirt</a></li>
                            <li><a href="#">Mens</a></li>
                            <li><a href="#">Womens</a></li>
                            <li><a href="#">Gift Cards</a></li>
                            <li><a href="#">Shoes</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Policies</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Terms of Use</a></li>
                            <li><a href="#">Privecy Policy</a></li>
                            <li><a href="#">Refund Policy</a></li>
                            <li><a href="#">Billing System</a></li>
                            <li><a href="#">Ticket System</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Company Information</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Store Location</a></li>
                            <li><a href="#">Affillate Program</a></li>
                            <li><a href="#">Copyright</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3 col-sm-offset-1">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <form action="#" class="searchform">
                            <input type="text" placeholder="Your email address" />
                            <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                            <p>Get the most recent updates from <br />our site and be updated your self...</p>
                        </form>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
            </div>
        </div>
    </div>
    
</footer><!--/Footer-->

templates/common/header.html
{% load static %}
<header id="header"><!--header-->
    <div class="header-middle"><!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-md-4 clearfix">
                    <div class="logo pull-left">
                        <a href="{% url 'home:index' %}"><img src="{% static 'images/home/logo.png' %}" alt="" /></a>
                    </div>
                </div>
                <div class="col-md-8 clearfix">
                    <div class="shop-menu clearfix pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href=""><i class="fa fa-user"></i> Account</a></li>
                            <li><a href="{% if user.is_authenticated %}{% url 'wishlist:wishlist' %}{% else %}{% url 'accounts:login' %}{% endif %}"><i class="fa fa-star"></i> Wishlist</a></li>
                            <li><a href="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li>
                            <li><a href="{% if user.is_authenticated %}{% url 'cart:cart' %}{% else %}{% url 'accounts:login' %}{% endif %}"><i class="fa fa-shopping-cart"></i> Cart</a></li>
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i> Logout</a></li>
                            {% else %}
                            <li><a href="{% url 'accounts:login' %}"><i class="fa fa-lock"></i> Login</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li><a href="{% url 'home:index' %}" class="active">Home</a></li>
                            <li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a href="shop.html">Products</a></li>
                                    <li><a href="#">Product Details</a></li> 
                                    <li><a href="checkout.html">Checkout</a></li> 
                                    <li><a href="cart.html">Cart</a></li> 
                                    <li><a href="login.html">Login</a></li> 
                                </ul>
                            </li> 
                            <li><a href="{% url 'contact:contactus' %}">Contact</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="search_box pull-right">
                        <form class="input-group">
                            <input type="text" class="" placeholder="Search" name="search" id="search"/>
                            <span class="input-group-btn">
                                <button class="btn btn-outline-secondary" type="submit"><img src="{% static 'images/home/searchicon.png' %}"/></button>
                           </span>   
                        </form>     
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

templates/common/sidebar.html
<div class="col-sm-3">
    <div class="left-sidebar">
        <h2>Category</h2>
        <div class="panel-group category-products" id="accordian"><!--category-products-->
            <div class="panel panel-default">
                {% for category in categories %}
                <div class="panel-heading">
                    <h4 class="panel-title">										
                        <a data-toggle="collapse" data-parent="#accordian" href="#{{category.id}}">
                            {% if category.subcategory_set.all %}
                            <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                            {% endif %}
                            {{category.category}}
                        </a>										
                    </h4>
                </div>
                <div id="{{category.id}}" class="panel-collapse collapse">
                    <div class="panel-body">
                        <ul>
                            {% for item in category.subcategory_set.all %}
                            <li><a href="{% url 'home:shop' item.id %}">{{item.sub_category}} </a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div><!--/category-products-->
        <div class="brands_products"><!--brands_products-->
            <h2>Brands</h2>
            <div class="brands-name">
                <ul class="nav nav-pills nav-stacked">
                    {% for brand in brands %}
                    <li><a href="#"> <span class="pull-right"></span>{{brand}}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div><!--/brands_products-->
        {% if max_value %}
        <div class="price-range"><!--price-range-->
            <h2>Price Range</h2>
            <div class="well text-center">
                <form action="" method="POST">
                    {% csrf_token %}
                    <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="{{max_value}}" data-slider-step="5" data-slider-value="[{{selected_value_min}},{{selected_value_max}}]" id="sl2" name='slider'><br />
                    <b class="pull-left">{{selected_value_min}}</b> <b class="pull-right">{{selected_value_max}}</b><br>
                    <button type="submit">Filter</button>
                </form>
                 
            </div>
        </div><!--/price-range-->
        
        <div class="shipping text-center"><!--shipping-->
            <img src="images/home/shipping.jpg" alt="" />
        </div><!--/shipping-->
        {% endif %}
    </div>
</div>